server:
  port: 8080
spring:
  application:
    name: interface_shielding_limit

  redis:
    host: 10.10.4.76
    port: 6379
    timeout: 10000
    database: 1
    password:
#    lettuce:
#      pool:
#        max-active: 8 #连接池的最大数据库连接数。设为0表示无限制
#        max-wait: -1 #最大建立连接等待时间。如果超过此时间将接到异常。设为-1表示无限制。
#        max-idle: 8 #最大空闲数
#        min-idle: 0